version: '1'
services:
  app-metric:
    image: metric:0.0.1
    container_name: metric
    command: pnpm run start
    env_file:
      - .env
    ports:
      - ${PORT}:8082
    tty: true
    restart: on-failure
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '4'
          memory: '8192MB'
        reservations:
          cpus: '1.5'
          memory: '1500MB'
    logging:
      driver: 'json-file'
      options:
        max-file: '5' # number of files or file count
        max-size: '100m' # file size
